version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    
  api:
    build: .
    ports:
     - 5050:5050
    environment:
      PORT: 5050
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: mongodb_api_db
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}